BEGIN;
CREATE TABLE IF NOT EXISTS WATCH ( ID INTEGER PRIMARY KEY AUTOINCREMENT, COMMENT TEXT, NAME TEXT, SERIAL TEXT, CREATED_AT TIMESTAMP );
insert into WATCH(ID,COMMENT,NAME,SERIAL,CREATED_AT) select _id,comment,name,serial,date_create from watches;
COMMIT;