package watchcheck.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import watchcheck.db.Watch;
import watchcheck.db.Log;

import watchcheck.db.WatchDao;
import watchcheck.db.LogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig watchDaoConfig;
    private final DaoConfig logDaoConfig;

    private final WatchDao watchDao;
    private final LogDao logDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        watchDaoConfig = daoConfigMap.get(WatchDao.class).clone();
        watchDaoConfig.initIdentityScope(type);

        logDaoConfig = daoConfigMap.get(LogDao.class).clone();
        logDaoConfig.initIdentityScope(type);

        watchDao = new WatchDao(watchDaoConfig, this);
        logDao = new LogDao(logDaoConfig, this);

        registerDao(Watch.class, watchDao);
        registerDao(Log.class, logDao);
    }
    
    public void clear() {
        watchDaoConfig.getIdentityScope().clear();
        logDaoConfig.getIdentityScope().clear();
    }

    public WatchDao getWatchDao() {
        return watchDao;
    }

    public LogDao getLogDao() {
        return logDao;
    }

}
