package watchcheck.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOG.
 */
public class Log implements java.io.Serializable {

    private Long id;
    private long watchId;
    private int period;
    /** Not-null value. */
    private java.util.Date referenceTime;
    /** Not-null value. */
    private java.util.Date watchTime;
    private String position;
    private Integer temperature;
    private String comment;

    public Log() {
    }

    public Log(Long id) {
        this.id = id;
    }

    public Log(Long id, long watchId, int period, java.util.Date referenceTime, java.util.Date watchTime, String position, Integer temperature, String comment) {
        this.id = id;
        this.watchId = watchId;
        this.period = period;
        this.referenceTime = referenceTime;
        this.watchTime = watchTime;
        this.position = position;
        this.temperature = temperature;
        this.comment = comment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getWatchId() {
        return watchId;
    }

    public void setWatchId(long watchId) {
        this.watchId = watchId;
    }

    public int getPeriod() {
        return period;
    }

    public void setPeriod(int period) {
        this.period = period;
    }

    /** Not-null value. */
    public java.util.Date getReferenceTime() {
        return referenceTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReferenceTime(java.util.Date referenceTime) {
        this.referenceTime = referenceTime;
    }

    /** Not-null value. */
    public java.util.Date getWatchTime() {
        return watchTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWatchTime(java.util.Date watchTime) {
        this.watchTime = watchTime;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public Integer getTemperature() {
        return temperature;
    }

    public void setTemperature(Integer temperature) {
        this.temperature = temperature;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
